typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=240

typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=true
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION=''

typeset -g POWERLEVEL9K_DIR_FOREGROUND=209
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=209

typeset -g POWERLEVEL9K_DIR_CLASSES=(
'~(|/*)'       HOME     '')

typeset -g POWERLEVEL9K_DIR_HOME_VISUAL_IDENTIFIER_EXPANSION=''
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_SHORTENED_FOREGROUND=4
typeset -g POWERLEVEL9K_DIR_HOME_ANCHOR_FOREGROUND=4
