#! /bin/sh

~/.config/polybar/polybar.sh &

feh --randomize --bg-fill ~/Pictures/Wallpapers/ --no-fehbg

sxhkd &

bspc config border_width         2
bspc config window_gap          10
bspc config top_padding         35

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc config focused_border_color "#81A1C1"
bspc config normal_border_color  "#2f343f"
bspc config presel_feedback_color "#81A1C1"


bspc rule -a Alacritty desktop='^1' focus=on follow=on
bspc rule -a kitty desktop='^1' focus=on follow=on
bspc rule -a St desktop='^1' focus=on follow=on
bspc rule -a Termite desktop='^1' focus=on follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Brave-browser desktop='^2' focus=on follow=on
bspc rule -a Zathura desktop='^5' focus=on state=tiled follow=on
bspc rule -a code-oss desktop='^5' follow=on focus=on
bspc rule -a feh desktop='^6' state=tiled follow=on
bspc rule -a Org.gnome.Nautilus desktop='^6' follow=on focus=on
bspc rule -a mpv desktop='^8' follow=on focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a TelegramDesktop desktop='^9' follow=on
bspc rule -a discord desktop='^10'  follow=on
bspc rule -a Pavucontrol desktop='^10'  follow=on
bspc rule -a ffplay state=floating sticky=on

picom --experimental-backends -b

# Set Cursor
xsetroot -cursor_name left_ptr

nm-applet &

xautolock -time 5 -corners --00 -detectsleep -locker "~/.config/scripts/lock.sh"  -notify 30  -notifier "notify-send -u critical '􀎠 xautolock' 'Suspending in 30 secs...'" &
setxkbmap -option caps:escape

~/.config/bspwm/scripts/dual.sh
~/.config/bspwm/scripts/last_node &

# to cache files 
timeout 15s nvim &
