#!/bin/sh

pgrep -x transmission-da || (transmission-daemon && sleep 3)
transmission-remote -a $@ && notify-send -u normal "􀓃  Transmission" "<a href=\"http://localhost:9091/transmission/web/ \"> Torrent Added</a>"
