#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12
bspc config top_padding         30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color  "#2f343f"

bspc rule -a kitty desktop='^1' focus=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Zathura desktop='^3' focus=on state=tiled follow=on
bspc rule -a Spotify desktop='^4'
bspc rule -a 'spotify' desktop='^4'
bspc rule -a vlc desktop='^4' follow=on focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a feh state=floating follow=on

# Compton
compton &

# Polybar
~/.config/polybar/launchi3.sh &

# feh
feh --randomize --bg-fill ~/Pictures/Wallpapers
# feh --bg-fill /home/george/Pictures/polygon.png

# Set Cursor
xsetroot -cursor_name left_ptr
