#! /bin/sh

~/.config/polybar/polybar.sh &

feh --randomize --bg-fill ~/Pictures/Wallpapers/

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap          10
bspc config top_padding         30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config focused_border_color "#d8dee8"
bspc config normal_border_color  "#2f343f"
bspc config presel_feedback_color "#ff5c57"

bspc rule -a kitty desktop='^1' focus=on
bspc rule -a Termite desktop='^1' focus=on follow=on
bspc rule -a firefox desktop='^2' focus=on follow=on
bspc rule -a Zathura desktop='^3' focus=on state=tiled follow=on
bspc rule -a vlc desktop='^4' follow=on focus=on
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a feh state=floating follow=on

# Compton
killall picom;picom -b

# Set Cursor
xsetroot -cursor_name left_ptr

nm-applet &

xautolock -time 10 -corners --00 -locker "~/.config/scripts/lock.sh suspend"  -notify 30  -notifier "notify-send -u critical '􀎠 xautolock' 'Suspending in 30 secs...'" &

setxkbmap -option caps:escape
